on:
  push:
    branches: ["main"]
    paths: "events.json"

jobs:
  event-update:
    runs-on: ubuntu-latest
    name: Update events in music page
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Event Updater
        run: "node ./.github/actions/events-updater"
      - name: commit files
        run: |
          git config --local user.name "events-updater[bot]"
          git commit -am "Update music.html"
      - name: push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

